# Generated by Django 3.2.14 on 2022-08-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_product_name', models.CharField(max_length=100)),
                ('brand_picture', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('brand_qr_code_url', models.CharField(max_length=500)),
                ('brand_qr_code_picture', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('brand_user_name', models.CharField(max_length=100)),
                ('brand_user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
