# Generated by Django 3.2.14 on 2022-08-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_picture',
            new_name='brand_logo',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brand_user_email',
        ),
    ]
