# Generated by Django 3.2.14 on 2022-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20220805_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brandlogos/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_product_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_qr_code_picture',
            field=models.ImageField(blank=True, null=True, upload_to='brandqrcodes/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_qr_code_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_user_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
