# Generated by Django 3.2.15 on 2022-09-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20220812_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300)),
                ('user_password', models.CharField(max_length=300)),
                ('user_info_qrcode', models.ImageField(upload_to='userqrcodes/')),
            ],
        ),
    ]
